spring.application.name=web-news-application
spring.datasource.url=jdbc:postgresql://localhost:5432/web_news_db
spring.datasource.username=postgres
spring.datasource.password=Arh150307
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
