# ????? ???????
spring.application.name=web-news-application

# ??????????? ?? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/web_news_db
spring.datasource.username=postgres
spring.datasource.password=root

# ???????????? Hibernate ?? JPA
# create-drop: ??????? ?? ??????? ??????? ?????? ??? ??????? ??????? (???????? ??? ????????)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ????????? ?????????? ?????? Spring, ??? ?? ??????????? ??????? 401
spring.mvc.favicon.enabled=false

# ???????????? ????????? (???????? ?????? ??????? ??????????? ? ???????)
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

# ?????? ???? ??? JSON (??? ?????? ???? ?????? ??????)
spring.jackson.serialization.write-dates-as-timestamps=false